/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package monnickendam.com.ia;

import java.io.File;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.File;

import java.io.FileInputStream;

import java.io.FileNotFoundException;

import java.io.FileOutputStream;

import java.io.IOException;

import java.io.ObjectInputStream;

import java.io.ObjectOutputStream;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author elie
 */
public class NewFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewFrame
     */
    public NewFrame() {
        initComponents();
        loadDatabaseFiles();
        SetIngredientTableHeaders();
        
    }
    
    private FoodDB WorkingDB = null;
    private Boolean DBLoadedState = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Today = new javax.swing.JPanel();
        Meals = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mealsTable = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        mealSearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Stats = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        LabelTotalItems = new javax.swing.JLabel();
        LabelDrinkCount = new javax.swing.JLabel();
        LabelMealCount = new javax.swing.JLabel();
        LabelSnackCount = new javax.swing.JLabel();
        DBInfoRefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        NewDBNameField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        CreateDB = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        RefreshList = new javax.swing.JButton();
        DatabaseSelector = new javax.swing.JComboBox<>();
        LoadSelectedDB = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ManualSave = new javax.swing.JButton();
        ExportDBToFile = new javax.swing.JButton();
        DemoData = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        DebugSHORT = new javax.swing.JLabel();
        DebugLONG = new javax.swing.JLabel();
        DebugPATH = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        infoPanel5 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        brandField = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        sizeField = new javax.swing.JTextField();
        typeComboBox = new javax.swing.JComboBox<>();
        quantityLabel5 = new javax.swing.JLabel();
        UnitLabel = new javax.swing.JLabel();
        macroPanel2 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        calorieField = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        proteinField = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        carbField = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        fatField = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        infoPanel6 = new javax.swing.JPanel();
        quantityLabel6 = new javax.swing.JLabel();
        AddToMealListButton = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        RecipeInfoRadio = new javax.swing.JRadioButton();
        ClearFieldsButton = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        IngredientQuantityField = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        IngredientQuantityType = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        IngredientTable = new javax.swing.JTable();
        AddIngredient = new javax.swing.JButton();
        NewIngredientTextField = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        RecipeTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(930, 650));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(930, 650));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(930, 650));

        Today.setMaximumSize(new java.awt.Dimension(930, 650));
        Today.setMinimumSize(new java.awt.Dimension(930, 650));

        javax.swing.GroupLayout TodayLayout = new javax.swing.GroupLayout(Today);
        Today.setLayout(TodayLayout);
        TodayLayout.setHorizontalGroup(
            TodayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TodayLayout.setVerticalGroup(
            TodayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Today", Today);

        mealsTable.setAutoCreateRowSorter(true);
        mealsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(mealsTable);

        jRadioButton1.setText("Meal");

        jRadioButton2.setText("Snack");

        jRadioButton3.setText("Drink");

        jRadioButton4.setSelected(true);
        jRadioButton4.setText("All");

        jLabel2.setText("Filter");

        jLabel5.setText("Search");

        javax.swing.GroupLayout MealsLayout = new javax.swing.GroupLayout(Meals);
        Meals.setLayout(MealsLayout);
        MealsLayout.setHorizontalGroup(
            MealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
            .addGroup(MealsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mealSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MealsLayout.setVerticalGroup(
            MealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MealsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel2)
                    .addComponent(mealSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Meals", Meals);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Database Info"));
        jPanel1.setMaximumSize(new java.awt.Dimension(154, 169));
        jPanel1.setMinimumSize(new java.awt.Dimension(154, 169));

        jLabel11.setText("Total Items");

        jLabel12.setText("Drinks");

        jLabel14.setText("Meals");

        jLabel16.setText("Snacks");

        LabelTotalItems.setFont(new java.awt.Font("Liberation Sans", 2, 13)); // NOI18N
        LabelTotalItems.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelTotalItems.setText("       ");

        LabelDrinkCount.setFont(new java.awt.Font("Liberation Sans", 2, 13)); // NOI18N
        LabelDrinkCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelDrinkCount.setText("        ");

        LabelMealCount.setFont(new java.awt.Font("Liberation Sans", 2, 13)); // NOI18N
        LabelMealCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelMealCount.setText("     ");

        LabelSnackCount.setFont(new java.awt.Font("Liberation Sans", 2, 13)); // NOI18N
        LabelSnackCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelSnackCount.setText("      ");

        DBInfoRefresh.setText("Refresh");
        DBInfoRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DBInfoRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DBInfoRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTotalItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelDrinkCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelMealCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelSnackCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(LabelTotalItems))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(LabelDrinkCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(LabelMealCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(LabelSnackCount))
                .addGap(18, 18, 18)
                .addComponent(DBInfoRefresh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Database Creator"));

        NewDBNameField.setToolTipText("");

        jLabel20.setText("Database Name");

        CreateDB.setText("Create DB");
        CreateDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreateDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewDBNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(NewDBNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateDB)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Database Selector"));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel22.setText("Select DB");

        RefreshList.setText("Refresh list");
        RefreshList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshListActionPerformed(evt);
            }
        });

        LoadSelectedDB.setText("Load");
        LoadSelectedDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadSelectedDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RefreshList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DatabaseSelector, 0, 319, Short.MAX_VALUE))
                    .addComponent(LoadSelectedDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(DatabaseSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RefreshList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoadSelectedDB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Database File Options"));

        ManualSave.setText("Manual Save");
        ManualSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualSaveActionPerformed(evt);
            }
        });

        ExportDBToFile.setText("Export DB to file");

        DemoData.setText("Add DEMO");
        DemoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManualSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExportDBToFile, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(DemoData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ManualSave)
                .addGap(18, 18, 18)
                .addComponent(ExportDBToFile)
                .addGap(18, 18, 18)
                .addComponent(DemoData)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Working Database Info"));

        jLabel19.setText("Shortname");

        jLabel21.setText("Longname");

        jLabel23.setText("Path");

        DebugSHORT.setFont(new java.awt.Font("Liberation Sans", 2, 13)); // NOI18N
        DebugSHORT.setText("No loaded DB");

        DebugLONG.setFont(new java.awt.Font("Liberation Sans", 2, 13)); // NOI18N
        DebugLONG.setText("No loaded DB");

        DebugPATH.setFont(new java.awt.Font("Liberation Sans", 2, 13)); // NOI18N
        DebugPATH.setText("No loaded DB");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DebugSHORT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DebugLONG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DebugPATH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(DebugSHORT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(DebugLONG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(DebugPATH))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout StatsLayout = new javax.swing.GroupLayout(Stats);
        Stats.setLayout(StatsLayout);
        StatsLayout.setHorizontalGroup(
            StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatsLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        StatsLayout.setVerticalGroup(
            StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(StatsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Misc", Stats);

        infoPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("General Info"));

        jLabel40.setText("Item Name");

        nameField.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        jLabel41.setText("Brand");

        jLabel42.setText("Type");

        jLabel43.setText("Size");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Snack", "Meal", "Drink" }));
        typeComboBox.setSelectedItem("");
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        UnitLabel.setText("   ");

        javax.swing.GroupLayout infoPanel5Layout = new javax.swing.GroupLayout(infoPanel5);
        infoPanel5.setLayout(infoPanel5Layout);
        infoPanel5Layout.setHorizontalGroup(
            infoPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(infoPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(jLabel41)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameField)
                    .addComponent(brandField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(typeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(infoPanel5Layout.createSequentialGroup()
                        .addComponent(sizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(infoPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UnitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))))
                .addContainerGap())
        );
        infoPanel5Layout.setVerticalGroup(
            infoPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(brandField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(sizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityLabel5)
                    .addComponent(UnitLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        macroPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Macronutrients per 100 g/ml"));

        jLabel44.setText("Calories");

        calorieField.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        jLabel45.setText("kcal");

        jLabel46.setText("Protein");

        jLabel47.setText("g");

        jLabel48.setText("Carbohydrates");

        jLabel49.setText("Fats");

        jLabel50.setText("g");

        jLabel51.setText("g");

        javax.swing.GroupLayout macroPanel2Layout = new javax.swing.GroupLayout(macroPanel2);
        macroPanel2.setLayout(macroPanel2Layout);
        macroPanel2Layout.setHorizontalGroup(
            macroPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(macroPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(macroPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(macroPanel2Layout.createSequentialGroup()
                        .addGroup(macroPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel44))
                        .addGap(49, 49, 49)
                        .addGroup(macroPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proteinField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calorieField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(macroPanel2Layout.createSequentialGroup()
                        .addGroup(macroPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(macroPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(macroPanel2Layout.createSequentialGroup()
                                .addComponent(fatField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(macroPanel2Layout.createSequentialGroup()
                                .addComponent(carbField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(macroPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addContainerGap())
        );
        macroPanel2Layout.setVerticalGroup(
            macroPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(macroPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(macroPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(calorieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(macroPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(proteinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(macroPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(carbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(macroPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(fatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Final Step"));

        AddToMealListButton.setText("Add to Meal List");
        AddToMealListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToMealListButtonActionPerformed(evt);
            }
        });

        RecipeInfoRadio.setText("Add Recipe Info?");

        ClearFieldsButton.setText("Clear all fields");
        ClearFieldsButton.setToolTipText("");
        ClearFieldsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearFieldsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoPanel6Layout = new javax.swing.GroupLayout(infoPanel6);
        infoPanel6.setLayout(infoPanel6Layout);
        infoPanel6Layout.setHorizontalGroup(
            infoPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanel6Layout.createSequentialGroup()
                .addGroup(infoPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, infoPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ClearFieldsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, infoPanel6Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(quantityLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, infoPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RecipeInfoRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(infoPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddToMealListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        infoPanel6Layout.setVerticalGroup(
            infoPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RecipeInfoRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddToMealListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClearFieldsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(quantityLabel6))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(macroPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(infoPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(macroPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(241, 241, 241))
        );

        jTabbedPane2.addTab("General Info", jPanel12);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingredients"));
        jPanel14.setPreferredSize(new java.awt.Dimension(245, 235));

        jLabel52.setText("Ingredient");

        jLabel53.setText("Quantity");

        IngredientQuantityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "ml", "tsp", "tbsp", "l", "g", "kg", "misc." }));

        IngredientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(IngredientTable);

        AddIngredient.setText("Add");
        AddIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIngredientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel52)
                            .addComponent(jLabel53))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(IngredientQuantityField, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IngredientQuantityType, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NewIngredientTextField)))
                    .addComponent(AddIngredient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(NewIngredientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IngredientQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel53)
                            .addComponent(IngredientQuantityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddIngredient)
                        .addGap(0, 169, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Recipe"));
        jPanel15.setPreferredSize(new java.awt.Dimension(245, 235));

        RecipeTextArea.setColumns(20);
        RecipeTextArea.setRows(5);
        jScrollPane7.setViewportView(RecipeTextArea);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
                .addGap(89, 89, 89))
        );

        jTabbedPane2.addTab("Recipe Info", jPanel13);

        jTabbedPane1.addTab("Add", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddToMealListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToMealListButtonActionPerformed
        AddToMealList();
    }//GEN-LAST:event_AddToMealListButtonActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        switch (typeComboBox.getSelectedItem().toString()) {
            case "Drink" -> UnitLabel.setText("ml");
            case "Snack", "Meal" -> UnitLabel.setText("g");
            default -> UnitLabel.setText(""); // fallback or handle unknown type
        }
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void DemoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoDataActionPerformed
        AddDemoData();
    }//GEN-LAST:event_DemoDataActionPerformed

    private void ManualSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualSaveActionPerformed
        SaveDB();
    }//GEN-LAST:event_ManualSaveActionPerformed

    private void LoadSelectedDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadSelectedDBActionPerformed
        String selected = DatabaseSelector.getSelectedItem().toString();
        String TempDBPath = "src/main/java/monnickendam/com/ia/dbs/" + selected + ".db";

        if (LoadDB(new File(TempDBPath))) {
            String baseName = selected;

            DebugSHORT.setText(baseName);             // e.g., "temp"
            DebugLONG.setText(baseName + ".db");      // e.g., "temp.db"
            DebugPATH.setText(TempDBPath);
            RefreshDBInfo();
        }

    }//GEN-LAST:event_LoadSelectedDBActionPerformed

    private void RefreshListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshListActionPerformed
        loadDatabaseFiles();
    }//GEN-LAST:event_RefreshListActionPerformed

    // ALL BUTTON INTERACTIONS
    
    private void CreateDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateDBActionPerformed

        // CREATE DATABSE

        File dir = new File("src/main/java/monnickendam/com/ia/dbs");

        if (!dir.exists()) {
            if (!dir.mkdirs()) {
                System.out.println("Failed to create directory: " + dir.getAbsolutePath());
                return;
            }
        }

        String name = NewDBNameField.getText();
        StringBuilder sb = new StringBuilder(name);

        for (int i = 0; i < sb.length(); i++) {
            if (sb.charAt(i) == ' ') {
                sb.setCharAt(i, '_');
            }
        }

        name = sb.toString();
        
        if (name.equals("")) {
            return;
        }

        File file = new File(dir, name + ".db");

        try {
            if (file.createNewFile()) {
                System.out.println("File created: " + file.getAbsolutePath());

                try {
                    // CREATE FILE STREAM
                    FileOutputStream f = new FileOutputStream(file);
                    ObjectOutputStream o = new ObjectOutputStream(f);

                    // WRITE PERSON OBJECTS (p1 AND p2) TO THE FILE (CAN WRITE ALL OBJECTS IN A LINKEDLIST IF YOU USE A LOOP)
                    FoodDB newDB = new FoodDB();
                    o.writeObject(newDB);

                    // CLOSE FILE STREAM
                    o.close();
                    f.close();

                } catch (Exception e) {
                    System.out.println("Error.");
                }

            } else {
                System.out.println("File already exists: " + file.getAbsolutePath());
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        NewDBNameField.setText(""); // Clear input

        loadDatabaseFiles();
    }//GEN-LAST:event_CreateDBActionPerformed

    private void DBInfoRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBInfoRefreshActionPerformed
        RefreshDBInfo();
    }//GEN-LAST:event_DBInfoRefreshActionPerformed

    private void ClearFieldsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearFieldsButtonActionPerformed
        // Clear input fields
        nameField.setText("");
        brandField.setText("");
        sizeField.setText("");
        calorieField.setText("");
        proteinField.setText("");
        carbField.setText("");
        fatField.setText("");
        typeComboBox.setSelectedIndex(0);  // reset combo box to first item (optional)
    }//GEN-LAST:event_ClearFieldsButtonActionPerformed

    private void AddIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIngredientActionPerformed
        AddIngredientToTable();
    }//GEN-LAST:event_AddIngredientActionPerformed

    // MY FUNCTIONS
    
    private void pass() { System.out.println("Passing...."); }
    
    private void AddDemoData() {
    if (WorkingDB == null) {
        JOptionPane.showMessageDialog(this, "No database loaded.");
        return;
    }

    // ----- Drinks -----
    String[][] drinks = {
        {"Coca-Cola", "Coca-Cola", "Drink", "330", "ml", "139", "0", "35", "0"},
        {"Orange Juice", "Tropicana", "Drink", "250", "ml", "110", "2", "26", "0"},
        {"Iced Coffee", "Starbucks", "Drink", "250", "ml", "150", "5", "22", "5"},
        {"Green Tea", "Lipton", "Drink", "250", "ml", "0", "0", "0", "0"},
        {"Energy Drink", "Red Bull", "Drink", "250", "ml", "112", "1", "27", "0"},
        {"Chocolate Milk", "Nesquik", "Drink", "300", "ml", "170", "8", "25", "5"},
        {"Protein Shake", "MyProtein", "Drink", "330", "ml", "200", "20", "10", "7"},
        {"Almond Milk", "Alpro", "Drink", "250", "ml", "60", "2", "8", "2"},
        {"Fruit Smoothie", "Innocent", "Drink", "250", "ml", "150", "2", "34", "1"},
        {"Vitamin Water", "Glacéau", "Drink", "500", "ml", "120", "0", "32", "0"}
    };

    for (String[] d : drinks) {
        Meal m = new Meal(d[0], d[1], d[2], Double.valueOf(d[3]), d[4]);
        m.setMacros(Double.valueOf(d[5]), Double.valueOf(d[6]), Double.valueOf(d[7]), Double.valueOf(d[8]));
        WorkingDB.add(m);
    }

    // ----- Meals -----
    String[][] meals = {
        {"Chicken Burrito", "Chipotle", "Meal", "450", "g", "750", "42", "60", "28"},
        {"Cheeseburger", "McDonald's", "Meal", "300", "g", "530", "25", "41", "27"},
        {"Margherita Pizza", "Pizza Express", "Meal", "400", "g", "700", "30", "75", "25"},
        {"Pad Thai", "Thai Express", "Meal", "450", "g", "680", "20", "80", "20"},
        {"Beef Lasagna", "Stouffer's", "Meal", "370", "g", "600", "32", "45", "30"},
        {"Butter Chicken", "Patak's", "Meal", "400", "g", "650", "35", "50", "28"},
        {"Sushi Platter", "Itsu", "Meal", "350", "g", "520", "18", "65", "15"},
        {"Grilled Salmon", "Homemade", "Meal", "300", "g", "480", "35", "10", "30"},
        {"Tofu Stir-fry", "Wagamama", "Meal", "400", "g", "520", "22", "60", "20"},
        {"Pasta Alfredo", "Olive Garden", "Meal", "400", "g", "850", "20", "70", "50"}
    };

    for (String[] m : meals) {
        Meal meal = new Meal(m[0], m[1], m[2], Double.valueOf(m[3]), m[4]);
        meal.setMacros(Double.valueOf(m[5]), Double.valueOf(m[6]), Double.valueOf(m[7]), Double.valueOf(m[8]));
        WorkingDB.add(meal);
    }

    // ----- Snacks -----
    String[][] snacks = {
        {"Granola Bar", "Nature Valley", "Snack", "42", "g", "190", "3", "29", "7"},
        {"Trail Mix", "Kirkland", "Snack", "50", "g", "250", "6", "20", "15"},
        {"Potato Chips", "Lay's", "Snack", "28", "g", "150", "2", "15", "10"},
        {"Greek Yogurt", "Chobani", "Snack", "150", "g", "130", "12", "14", "4"},
        {"Protein Bar", "Quest", "Snack", "60", "g", "200", "20", "22", "8"},
        {"Popcorn", "Orville", "Snack", "30", "g", "120", "3", "21", "3"},
        {"Rice Cakes", "Quaker", "Snack", "18", "g", "70", "1", "14", "0"},
        {"Apple Slices", "Fresh", "Snack", "150", "g", "80", "0", "22", "0"},
        {"Nut Butter Pack", "Justin's", "Snack", "32", "g", "190", "6", "8", "16"},
        {"Chocolate Bar", "Cadbury", "Snack", "45", "g", "230", "2", "26", "13"}
    };

    for (String[] s : snacks) {
        Meal snack = new Meal(s[0], s[1], s[2], Double.valueOf(s[3]), s[4]);
        snack.setMacros(Double.valueOf(s[5]), Double.valueOf(s[6]), Double.valueOf(s[7]), Double.valueOf(s[8]));
        WorkingDB.add(snack);
    }

    JOptionPane.showMessageDialog(this, "30 demo meals added successfully.");
}

    private void loadDatabaseFiles() {
        File dir = new File("src/main/java/monnickendam/com/ia/dbs");

        if (!dir.exists() || !dir.isDirectory()) {
            JOptionPane.showMessageDialog(this, "Directory not found: " + dir.getAbsolutePath());
            return;
        }

        String[] files = dir.list((d, name) -> new File(d, name).isFile());

        if (files != null && files.length > 0) {
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

            for (String filename : files) {
                if (filename.endsWith(".db")) {
                    model.addElement(filename.substring(0, filename.length() - 3)); // remove ".db"
                } else {
                    model.addElement(filename); // fallback in case extension is missing
                }
            }

            DatabaseSelector.setModel(model);
        } else {
            JOptionPane.showMessageDialog(this, "No files found in directory.");
        }
    }
 
    private void SaveDB() {
        if (WorkingDB == null) {
            System.out.println("No database loaded to save.");
            return;
        }

        String dbName = DebugSHORT.getText(); // Get the base name, e.g., "MyDB"
        if (dbName == null || dbName.isEmpty()) {
            System.out.println("DebugSHORT is empty — cannot determine file name.");
            return;
        }

        // Sanitize filename
        dbName = dbName.replace(" ", "_");

        // Build file path
        File file = new File("src/main/java/monnickendam/com/ia/dbs", dbName + ".db");

        try {
            FileOutputStream fileOut = new FileOutputStream(file);
            ObjectOutputStream out = new ObjectOutputStream(fileOut);

            out.writeObject(WorkingDB);

            out.close();
            fileOut.close();

            System.out.println("Database saved to: " + file.getAbsolutePath());

        } catch (IOException e) {
            System.out.println("Failed to save database.");
            e.printStackTrace();
        }
    }

    private Boolean LoadDB(File file) {
        if (file == null || !file.exists()) {
            JOptionPane.showMessageDialog(this, "File not found.");
            return false;
        }

        try {
            // Open file input stream
            FileInputStream f = new FileInputStream(file);
            ObjectInputStream o = new ObjectInputStream(f);

            // Read the FoodDB object from file
            FoodDB loadedDB = (FoodDB) o.readObject();

            // Close streams
            o.close();
            f.close();

            // Set it as the current working database
            WorkingDB = loadedDB;
            DBLoadedState = true;
            System.out.println("Database loaded successfully from: " + file.getAbsolutePath());
            return true;

            // Optionally, update UI components if needed
            // updateUIWithDatabase(WorkingDB);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading database : " + e.getMessage());
            return false;
        }
    }

    private void RefreshDBInfo() {
        LabelTotalItems.setText(String.valueOf(WorkingDB.getItemCount()));
        LabelDrinkCount.setText(String.valueOf(WorkingDB.getDrinkCount()));
        LabelMealCount.setText(String.valueOf(WorkingDB.getMealCount()));
        LabelSnackCount.setText(String.valueOf(WorkingDB.getSnackCount()));
    }
    
    private void AddToMealList() {
    try {
        if (!DBLoadedState) {
            return;
        }
        // Extract and parse values from the UI
        String name = nameField.getText();
        String brand = brandField.getText();
        String type = typeComboBox.getSelectedItem().toString();
        double size = Double.parseDouble(sizeField.getText());
        
        String sizeType;
        switch (type) {
            case "Drink" -> sizeType = "ml";
            case "Snack", "Meal" -> sizeType = "g";
            default -> sizeType = ""; // fallback or handle unknown type
        }

        double calories = Double.parseDouble(calorieField.getText());
        double protein = Double.parseDouble(proteinField.getText());
        double carbs = Double.parseDouble(carbField.getText());
        double fats = Double.parseDouble(fatField.getText());

        // Create Meal object
        Meal newMeal = new Meal(name, brand, type, size, sizeType);
        newMeal.setMacros(calories, protein, carbs, fats);
        
        
        // Add Recipe info if desired
        if (RecipeInfoRadio.isSelected()) {
            // ADD INGREDIENTS
            
            DefaultTableModel model = (DefaultTableModel) IngredientTable.getModel();

            for (int i = 0; i < model.getRowCount(); i++) {
                String tempIngredientName = model.getValueAt(i, 0) != null ? model.getValueAt(i, 0).toString() : "";
    
                double tempQuantity = 0.0;
                try {
                    Object quantityObj = model.getValueAt(i, 1);
                    if (quantityObj != null && !quantityObj.toString().trim().isEmpty()) {
                        tempQuantity = Double.parseDouble(quantityObj.toString().trim());
                    }
                } catch (NumberFormatException e) {
                    System.out.println("Invalid quantity at row " + i + ": " + model.getValueAt(i, 1));
                    continue; // skip this row or handle as needed
                }

                String tempUnit = model.getValueAt(i, 2) != null ? model.getValueAt(i, 2).toString() : "";

                newMeal.AddIngredient(new Ingredient(tempIngredientName, tempQuantity, tempUnit));
            }
            
            // ADD RECIPE TEXT
            
            newMeal.setRecipe(RecipeTextArea.getText());

        }

        // Add to DB
        WorkingDB.add(newMeal);

        // Optionally confirm or refresh UI
        JOptionPane.showMessageDialog(this, "Meal added successfully!");
        // Clear input fields
        nameField.setText("");
        brandField.setText("");
        sizeField.setText("");
        calorieField.setText("");
        proteinField.setText("");
        carbField.setText("");
        fatField.setText("");
        typeComboBox.setSelectedIndex(0);  // reset combo box to first item (optional)
        RecipeTextArea.setText("");
        DefaultTableModel model = (DefaultTableModel) IngredientTable.getModel();
        model.setRowCount(0);

        


        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid number in size/macros field.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error adding meal: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void SetIngredientTableHeaders() {
        // Set preferred width of the third column (index 2)
        IngredientTable.getColumnModel().getColumn(2).setPreferredWidth(30);
        IngredientTable.getColumnModel().getColumn(2).setMaxWidth(40);
        IngredientTable.getColumnModel().getColumn(2).setMinWidth(30);
        
        // Set preferred width of the third column (index 2)
        IngredientTable.getColumnModel().getColumn(1).setPreferredWidth(65);
        IngredientTable.getColumnModel().getColumn(1).setMaxWidth(65);
        IngredientTable.getColumnModel().getColumn(1).setMinWidth(65);
        
        IngredientTable.removeColumn(IngredientTable.getColumnModel().getColumn(3));
        IngredientTable.getColumnModel().getColumn(0).setHeaderValue("Name");
        IngredientTable.getColumnModel().getColumn(1).setHeaderValue("Quantity");
        IngredientTable.getColumnModel().getColumn(2).setHeaderValue("");
        IngredientTable.getTableHeader().repaint();
        
        DefaultTableModel model = (DefaultTableModel) IngredientTable.getModel();

        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            boolean isEmpty = true;
            for (int j = 0; j < model.getColumnCount(); j++) {
                Object value = model.getValueAt(i, j);
                if (value != null && !value.toString().trim().isEmpty()) {
                    isEmpty = false;
                    break;
                }
            }
            if (isEmpty) {
                model.removeRow(i);
            }
        }
    }
    
    private void AddIngredientToTable() {
        DefaultTableModel model = (DefaultTableModel) IngredientTable.getModel();
        String name = NewIngredientTextField.getText();
        Double quant = Double.valueOf(IngredientQuantityField.getText());
        String quantType = IngredientQuantityType.getSelectedItem().toString();
        model.addRow(new Object[] { name, quant, quantType });
        
        // Clear fields
        NewIngredientTextField.setText("");
        IngredientQuantityField.setText("");
        IngredientQuantityType.setSelectedIndex(0);

    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddIngredient;
    private javax.swing.JButton AddToMealListButton;
    private javax.swing.JButton ClearFieldsButton;
    private javax.swing.JButton CreateDB;
    private javax.swing.JButton DBInfoRefresh;
    private javax.swing.JComboBox<String> DatabaseSelector;
    private javax.swing.JLabel DebugLONG;
    private javax.swing.JLabel DebugPATH;
    private javax.swing.JLabel DebugSHORT;
    private javax.swing.JButton DemoData;
    private javax.swing.JButton ExportDBToFile;
    private javax.swing.JTextField IngredientQuantityField;
    private javax.swing.JComboBox<String> IngredientQuantityType;
    private javax.swing.JTable IngredientTable;
    private javax.swing.JLabel LabelDrinkCount;
    private javax.swing.JLabel LabelMealCount;
    private javax.swing.JLabel LabelSnackCount;
    private javax.swing.JLabel LabelTotalItems;
    private javax.swing.JButton LoadSelectedDB;
    private javax.swing.JButton ManualSave;
    private javax.swing.JPanel Meals;
    private javax.swing.JTextField NewDBNameField;
    private javax.swing.JTextField NewIngredientTextField;
    private javax.swing.JRadioButton RecipeInfoRadio;
    private javax.swing.JTextArea RecipeTextArea;
    private javax.swing.JButton RefreshList;
    private javax.swing.JPanel Stats;
    private javax.swing.JPanel Today;
    private javax.swing.JLabel UnitLabel;
    private javax.swing.JTextField brandField;
    private javax.swing.JTextField calorieField;
    private javax.swing.JTextField carbField;
    private javax.swing.JTextField fatField;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JPanel infoPanel2;
    private javax.swing.JPanel infoPanel5;
    private javax.swing.JPanel infoPanel6;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel macroPanel2;
    private javax.swing.JTextField mealSearch;
    private javax.swing.JTable mealsTable;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField proteinField;
    private javax.swing.JLabel quantityLabel2;
    private javax.swing.JLabel quantityLabel5;
    private javax.swing.JLabel quantityLabel6;
    private javax.swing.JTextField sizeField;
    private javax.swing.JComboBox<String> typeComboBox;
    // End of variables declaration//GEN-END:variables

}
